# Generated by Django 5.2 on 2025-05-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
